version: '3'

services:

  gradle-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradle
    command: /home/gradle/start.sh
    volumes:
      - ./artefacts/gs-spring-boot-0.1.0.jar:/home/gradle/gs-spring-boot-0.1.0.jar    
   
