version: '3'

services:

  gradle-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradle
    volumes:
      - /opt/:/home/gradle/gs-spring-boot-master/initial/build/libs/
