version: '3'

services:

  gradle-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradle
    command: /home/gradle/start.sh
    volumes:
      - /root/12/*.jar:/home/gradle/*.jar    
    
